version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11

    working_directory: /go/src/github.com/acomagu/randtest
    environment:
      GO111MODULE: 'on'
    steps:
      - checkout
      - run: go test -race -v ./...
      - run:
          name: Send coverage
          command: |
            go get github.com/pierrre/gotestcover
            gotestcover -coverprofile=coverage.txt ./...
            bash <(curl -s https://codecov.io/bash)
